Config = {}

Config.Language = {
    ineedhelp = "[~e~Bill~q~]: Hey, are you interested in ~e~Stealing~q~ a House?",
	talktobill = "Press [~e~ENTER~q~] to Talk to Bill.",
    billtext1 = "[~e~Bill~q~]: I got beaten up and my pockets emptied in the brothel House across the street last night...",
    billtext2 = "[~e~Bill~q~]: The House is filled with Mad Women ... But it is also filled with treasure as they say ! How about robbing her ?",
    billtext3 = "[~e~Bill~q~]: If you accept you will need at least 1 ~e~Lockpick~q~ with you to Unlock the Door",
    billtext4 = "[~e~Bill~q~]: Go and steal them as much as possible ... if you find my red shirt it would be nice to bring it back to me please !",
    billtext5 = "[~e~Bill~q~]: Move to the location shown on the Map! ! You have ~e~30 Minutes~q~ before the brothel opens those doors !",
	toofar = "[~e~Bill~q~]: To Complete or Cancel the Mission, Move away from the Sector !",
	billacceptmission = "Press [~e~Enter~q~] to Accept",
	picklockdoorHouse = "Press [~e~Enter~q~] to Lock Pick the door !",
	doorlockedHouse = "Doors [~e~Locked~q~]",	
	houseunlocked = "Door Unlock! Go search the House!",
	brokelockhouse = "Your LockPick Broke ! Try Again !",	
	searchhouse = "Press [~e~Enter~q~] to Search !",
	searchinghouse = "Researching...",	
	luck1 = "You got [~e~Nothing~q~] Here !", -- change name here if you change the loot in the server.lua
	luck2 = "You found [~e~Bread~q~] !", -- change name here if you change the loot in the server.lua
	luck3 = "You found [~e~Water~q~] !", -- change name here if you change the loot in the server.lua
	luck4 = "You found [~e~LockPick~q~] !", -- change name here if you change the loot in the server.lua
	luck5 = "You got [~e~Nothing~q~] Here !", -- change name here if you change the loot in the server.lua
	luck6 = "You found [~e~Beer~q~] !", -- change name here if you change the loot in the server.lua
	luck7 = "You found [~e~Watch~q~] !", -- change name here if you change the loot in the server.lua
	luck8 = "You got [~e~Nothing~q~] Here !", -- change name here if you change the loot in the server.lua
	luck9 = "You found [~e~Leather~q~] !", -- change name here if you change the loot in the server.lua
	luck10 = "You found [~e~$5~q~] !", -- change money here if you change the loot in the server.lua
	allopen = "You Have [~e~Finish~q~] Search for all available Places.",
	women = "You have made too many [~e~Noises~q~] and the Housekeepers will take care of You !",
    failhouse = "You [~e~Fail~q~] Bill's Mission for: [~e~Too Far~q~] or [~e~Death~q~] or [~e~Time Elapsed~q~]",
    failtime = "[~e~Time Elapsed !~q~]",
	notnowhouse = "Not Now Hic! Come Back Later Hic!",
	done = "You Have [~e~Finish~q~] Bill's Mission !",
	repportsherifhouse = "Someone doing shit at the Brothel house",
    linehouse = "Press [~e~E~q~] on the Line !",
	sherifonline = "There is not enough Sheriff",
	lockpickinghouse = "Lockpicking in progress...",	
	nolockpickhouse = "You do not have [~e~LockPick~q~]",
}
Config.MinPoliceCount = 5 