// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
  defaultTemplateId: 'default', //This is the default template for 2 args1
  defaultAltTemplateId: 'defaultAlt', //This one for 1 arg
  templates: { //You can add static templates here
    'default': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder system"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type system">{0}</span></div></div></div></div>',

    'defaultAlt': '{0}',
    'print': '<pre>{0}</pre>',
    'print': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder system"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type system">{0}</span></div></div></div></div>',

    'example:important': '<h1>^2{0}</h1>',

    'ooc': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder normal"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type normal">OOC</span><b>{0}</b></div></div></div></div>',
    'oocl': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder normal"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type normal">OOCL</span><b>{0}</b></div></div></div></div>',
    'error': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder error"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type error">{0}</span></div></div></div></div>',
    'normal': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder normal"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type normal">{0}</span></div></div></div></div>',
    'report': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder report"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type report">Report</span><b>{0}</b></div></div></div></div>',
    'creport': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder report"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type report">{0}</span></div></div></div></div>',
    'success': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder success"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type success">{0}</span></div></div></div></div>',
    'warning': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder warning"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type warning">{0}</span></div></div></div></div>',
    'system': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder system"></div><div class="chatdata"><span><span class="label-msg-txt">{1}</span></span><div class="label-msg-details"><span class="label-msg-type system">{0}</span></div></div></div></div>',
    'emergency': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder emergency"></div><div class="chatdata"><span><span class="label-msg-txt">{0}</span></span><div class="label-msg-details"><span class="label-msg-type emergency">SYSTEM</span></div></div></div></div>',
    '911': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder emergency"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type emergency">911 #{0}</span><b>{1}</b></div></div></div></div>',
    '311': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder emergency"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type emergency">311 #{0}</span><b>{1}</b></div></div></div></div>',
    '911r': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder emergency"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type emergency">911 Reply #{0}</span><b>{1}</b></div></div></div></div>',
    '311r': '<div class="chat-message2"><div class="label-msg"><div class="nmdborder emergency"></div><div class="chatdata"><span><span class="label-msg-txt">{2}</span></span><div class="label-msg-details"><span class="label-msg-type emergency">311 Reply #{0}</span><b>{1}</b></div></div></div></div>',
  },
  fadeTimeout: 4000,
  suggestionLimit: 5,
  style: {
    background: 'transparent',
    width: '25%',
    height: '22vh',
  }
};

/*
  style: {
    background: 'rgba(255, 93, 0, 0.62)',
    border: '1px solid #000000',
    width: '38%',
    height: '22%',
  }
*/