RegisterCommand('guitar', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_SIT_GUITAR'))
    Citizen.Wait(65000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('puke', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_VOMIT_KNEEL'))
    Citizen.Wait(15000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('bartender', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_BARTENDER_CLEAN_GLASS'))
    Citizen.Wait(15000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('badass', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_BADASS'))
    Citizen.Wait(15000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('trumpet', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_TRUMPET'))
    Citizen.Wait(15000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('pee', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('world_human_pee'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('broom', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_BROOM'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('clipboard', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_CLIPBOARD'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('saw', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_SAW_WOOD'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('cig', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_SMOKE_NERVOUS_STRESSED'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('cig1', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_SMOKE'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('wine2', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_DRINK_CHAMPAGNE'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('brush', function(source)
    local ped = PlayerPedId()
    TaskStartScenarioInPlace(ped, GetHashKey('WORLD_HUMAN_HORSE_TEND_BRUSH_LINK'))
    Citizen.Wait(25000)
    ClearPedTasksImmediately(ped, true, true)
end)

RegisterCommand('watch', function(source)
    local ped = PlayerPedId()
    TaskItemInteraction(ped, GetHashKey("PROVISION_POCKET_WATCH_REUTLINGE"), GetHashKey("POCKET_WATCH_INSPECT_UNHOLSTER"), 1, 0, -1082130432)
end)

RegisterCommand('compass', function(source)
    local ped = PlayerPedId()
    TaskItemInteraction(ped, GetHashKey("PROVISION_PEARSONS_NAVAL_COMPASS"), GetHashKey("POCKET_WATCH_INSPECT_UNHOLSTER"), 1, 0, -1082130432)
end)



