-- * SELL ITEMS  * --

-- * TO ADD DECIMAL PRICES TO THE RANDOMPRICE DO IT LIKE THIST math.random(30, 50) / 100 >> this will equal to 0.30 to 0.50 or math.random(300, 500) / 100 will equal to 3.00 to 5.00

-- * THESE ARE JUST EXAMPLES YOU MUST CONFIGURE YOUR OWN STORES *--

Config.SellItems = {
    Valentine = {                                    -- name must be the same as  in the stores
        {
            itemLabel = "Pick Axe",                  -- Label of the item
            itemName = "pickaxe",                    -- same as in your database
            currencyType = "cash",                   -- cash or gold
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) , -- random price between 30 and 50 if randomprices is true in this store. adding a /100 the price will be in decimals
            desc = "sell pick axe",                  -- menu description
            category = "tools",                      -- category where this item will show up if set in the store config
            itemLimit = 0,                           -- limit of this item in the store to be sold for  all players
            -- weapon = false,                    -- set to true if you want to sell weapons, or delete this from items
        },
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell delicious hand picked apples",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Bread",
            itemName = "bread",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(1, 3),
            desc = "sell bread",
            category = "food",
            itemLimit = 10,
        },
        {
            itemLabel = "water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell water",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Revolver Lemat",
            itemName = "WEAPON_REVOLVER_LEMAT",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave 0
        },
        {
            itemLabel = "Knife",
            itemName = "WEAPON_MELEE_KNIFE",
            currencyType = "cash",
            sellprice = 40,
            randomprice = math.random(30, 50),
            desc = "sell pick axe",
            category = "weapons",
            weapon = true, -- add this if you want to sell weapons in the store
            itemLimit = 0, -- delete if you dont want a limit to be able to sell or leave 0
        },


    },
    Rhodes = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Strawberry = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Blackwater = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Armadillo = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Tumbleweed = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    StDenis = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Vanhorn = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1,2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    BlackwaterFishing = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    Wapiti = {
        {
            itemLabel = "Apple",
            itemName = "apple",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "Water",
            itemName = "water",
            currencyType = "cash",
            sellprice = 10,
            randomprice = math.random(15),
            desc = "sell",
            category = "food",
            itemLimit = 0,
        },
        {
            itemLabel = "bandage",
            itemName = "bandage",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell bandage",
            category = "meds",
            itemLimit = 0,
        },
        {
            itemLabel = "Pick Axe",
            itemName = "pickaxe",
            currencyType = "cash",
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5) ,
            desc = "sell pick axe",
            category = "tools",
            itemLimit = 0,
        },
    },
    weedsell = {
        {
            itemLabel = "weedbuds",
            itemName = "weedbuds",
            currencyType = "cash",
            sellprice = 50,
            randomprice = math.random(40, 55),
            desc = "sell",
            category = "weed",
            itemLimit = 0,
        },
        {
            itemLabel = "watering Bucket",
            itemName = "wateringbucket",
            currencyType = "cash",
            sellprice = 1,
            randomprice = math.random(15),
            desc = "sell",
            category = "tool",
            itemLimit = 0,
        },
     
    },
    farm = {                                    -- name must be the same as  in the stores
        {
            itemLabel = "Alaskan Ginseng",                  -- Label of the item
            itemName = "Alaskan_Ginseng",                    -- same as in your database
            currencyType = "cash",                   -- cash or gold
            sellprice = 5,                          -- fixed price if randomprices is false in this stores config
            randomprice = math.random(3, 5), -- random price between 30 and 50 if randomprices is true in this store. adding a /100 the price will be in decimals
            desc = "sell Alaskan Ginseng",                  -- menu description
            category = "Farming",                      -- category where this item will show up if set in the store config
            itemLimit = 0,                           -- limit of this item in the store to be sold for  all players
            -- weapon = false,                    -- set to true if you want to sell weapons, or delete this from items
        },
        {
            itemLabel = "Black Berry",
            itemName = "Black_Berry",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(1, 5),
            desc = "sell delicious hand Black Berry",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "Black Currant",
            itemName = "Black_Currant",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(1, 5),
            desc = "sell delicious hand Black Currant",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "Red Raspberry",
            itemName = "Red_Raspberry",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(3),
            desc = "sell delicious hand Red Raspberry",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "honey",
            itemName = "honey",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(5, 10),
            desc = "sell delicious hand honey",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "wood",
            itemName = "wood",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(3),
            desc = "sell wood",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "rubber",
            itemName = "rubber",
            currencyType = "cash",
            sellprice = 3,
            randomprice = math.random(3, 5),
            desc = "sell rubber",
            category = "Farming",
            itemLimit = 0,
        },
       
        {
            itemLabel = "fibers",
            itemName = "fibers",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(3),
            desc = "sell fibers",
            category = "Farming",
            itemLimit = 0,
        },
        {
            itemLabel = "salt",
            itemName = "salt",
            currencyType = "cash",
            sellprice = 2,
            randomprice = math.random(3),
            desc = "sell salt",
            category = "Farming",
            itemLimit = 0,
        },


    },
    mineshop = {
        {
            itemLabel = "clay",
            itemName = "clay",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "coal",
            itemName = "coal",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(6),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "copper",
            itemName = "copper",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "iron",
            itemName = "iron",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(6),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "nitrite",
            itemName = "nitrite",
            currencyType = "cash",
            sellprice = 4,
            randomprice = math.random(3, 5),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "rock",
            itemName = "rock",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(6),
            desc = "sell mine item",
            category = "mine",
            itemLimit = 0,
        },
        {
            itemLabel = "hatchet",
            itemName = "hatchet",
            currencyType = "cash",
            sellprice = 5,
            randomprice = math.random(6),
            desc = "sell mine item",
            category = "tools",
            itemLimit = 0,
        },
        {
            itemLabel = "pickaxe",
            itemName = "pickaxe",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(1, 2),
            desc = "sell",
            category = "tools",
            itemLimit = 0,
        },
        {
            itemLabel = "shovel",
            itemName = "shovel",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(2),
            desc = "sell",
            category = "tools",
            itemLimit = 0,
        },
        {
            itemLabel = "goldpan",
            itemName = "goldpan",
            currencyType = "cash",
            buyprice = 1,
            randomprice = math.random(2),
            desc = "sell",
            category = "tools",
            itemLimit = 0,
        },
     
     
    },
    pelttrader = {

        { itemLabel = "Heroin", itemName = "heroin", currencyType = "cash", sellprice = 20, randomprice = math.random(10, 20) /50, desc = "Sell Heroin", category = "Meds", itemLimit = 0, },
        { itemLabel = "Hemp", itemName = "hemp", currencyType = "cash", sellprice = 20, randomprice = math.random(20) /50, desc = "Sell Hemp", category = "Meds", itemLimit = 0, },
        { itemLabel = "Bandage", itemName = "bandage", currencyType = "cash", sellprice = 20, randomprice = math.random(20) /50, desc = "Sell Bandage", category = "Meds", itemLimit = 0, },	
        { itemLabel = "Woodpecker", itemName = "woodpeck01_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Woodpecker" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Woodpecker 2", itemName = "woodpeck02_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Woodpecker 2" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Western rattlesnake pelt", itemName = "wsnakes", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Western rattlesnake pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Watersnake pelt", itemName = "wsnakeskin", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Watersnake pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Wolf heart", itemName = "wolfheart", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Wolf heart" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Wolf skin", itemName = "wolfpelt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Wolf skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Wolf tooth", itemName = "wolftooth", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Wolf tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Turkey beak", itemName = "turkeyb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Turkey beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Turkey feather", itemName = "turkeyf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Turkey feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Turtle Shell", itemName = "TurtleShell", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Turtle Shell" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Turtle tooth", itemName = "turtlet", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Turtle tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Desert Toad", itemName = "toaddesert_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Desert Toad" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Poisoned Toad", itemName = "toadpoison_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Poisoned Toad" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Toad", itemName = "toad_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Toad" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Black Squirrel", itemName = "squirrel_black_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Black Squirrel" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Gray Squirrel", itemName = "squirrel_grey_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Gray Squirrel" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Red Squirrel", itemName = "squirrel_red_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Red Squirrel" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Small Leather", itemName = "Small_Leather", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Small Leather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Snake Skin", itemName = "SnakeSkin", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Snake Skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Snake tooth", itemName = "snaket", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Snake tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Scarlet songbird", itemName = "songbird2_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Scarlet songbird" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Songbird", itemName = "songbird_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Songbird" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Common Sparrow", itemName = "sparrow0_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Common Sparrow" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Sparrow", itemName = "sparrow1_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Sparrow" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Golden Sparrow", itemName = "sparrow2_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Golden Sparrow" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Sheep head", itemName = "sheephead", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Sheep head" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Roseta Spoonbill beak", itemName = "rspoonb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Roseta Spoonbill beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Roseta Spoonbill feather", itemName = "rspoonf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Roseta Spoonbill feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Rat", itemName = "rat_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Rat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Raven Claws", itemName = "ravenc", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Raven Claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Raven Feather", itemName = "ravenf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Raven Feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Ram Horn", itemName = "ramhorn", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Ram Horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Ram Pelt", itemName = "rams", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Ram Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Rabbitfoot", itemName = "rabbitpaw", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Rabbitfoot" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Rabbit Skin", itemName = "rabbits", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Rabbit Skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Raccoon Skin", itemName = "raccoons", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Raccoon Skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Raccoon Tooth", itemName = "raccoont", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Raccoon Tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Quail Beak", itemName = "quailb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Quail Beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Quail Feather", itemName = "quailf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Quail Feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Prairie Chicken Beak", itemName = "prairib", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Prairie Chicken Beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Prairie Chicken Feather", itemName = "prairif", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Prairie Chicken Feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pronghorn Horn", itemName = "pronghornh", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pronghorn Horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pronghorn Skin", itemName = "prongs", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pronghorn Skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pig fat", itemName = "porkfat", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pig fat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pigeon", itemName = "pigeon_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pigeon" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pig pelt", itemName = "pigs", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pig pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Peasant beak", itemName = "peasantb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Peasant beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Peasant feather", itemName = "peasantf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Peasant feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Peccary pelt", itemName = "pecaris", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Peccary pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pelican beak", itemName = "pelicanb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pelican beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pelican feather", itemName = "pelicanf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Pelican feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Hooded Oriole", itemName = "oriole2_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Hooded Oriole" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Oriole", itemName = "oriole_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Oriole" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Owl feather", itemName = "owlf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Owl feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Owl claws", itemName = "owlt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Owl claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Angus Bull horn", itemName = "oxhorn", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Angus Bull horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Angus Bull pelt", itemName = "oxs", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Angus Bull pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Panther eyes", itemName = "panthere", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Panther eyes" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Panther skin", itemName = "panthers", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Panther skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Opossum claws", itemName = "opossumc", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Opossum claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Opossum skin", itemName = "opossums", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Opossum skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Muskrat skin", itemName = "muskrats", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Muskrat skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Moose Antlers", itemName = "mooseantler", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Moose Antlers" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Moose pelt", itemName = "mooses", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Moose pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Common loon beak", itemName = "loonb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Common loon beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Common loon feather", itemName = "loonf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Common loon feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Lizard foot", itemName = "lizardl", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Lizard foot" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Lizard pelt", itemName = "lizards", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Lizard pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Great Blue Heron Beak", itemName = "kbirdb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Great Blue Heron Beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Great Blue Heron Feather", itemName = "kbirdf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Great Blue Heron Feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Hawk feather", itemName = "hawkf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Hawk feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Hawk claws", itemName = "hawkt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Hawk claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Goose beak", itemName = "gooseb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Goose beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Goose feather", itemName = "goosef", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Goose feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Goose Egg", itemName = "Goose_Egg_4", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Goose Egg" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Green Iguana pelt", itemName = "gleguans", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Green Iguana pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Goat head", itemName = "goathead", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Goat head" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Goat pelt", itemName = "goats", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Goat pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Gold Fish", itemName = "goldfish", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Gold Fish" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Aligator Egg 3", itemName = "Gator_Egg_3", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Aligator Egg 3" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Aligator Egg 4", itemName = "Gator_Egg_4", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Aligator Egg 4" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Aligator Egg 5", itemName = "Gator_Egg_5", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Aligator Egg 5" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Grizzly Bear skin", itemName = "gbears", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Grizzly Bear skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Poisoned Frogbull", itemName = "frogbull2_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Poisoned Frogbull" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Frogbull", itemName = "frogbull_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Frogbull" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Blacktail rattlesnake pelt", itemName = "fsnakes", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Blacktail rattlesnake pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Foxskin", itemName = "foxskin", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Foxskin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Fox tooth", itemName = "foxt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Fox tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Animal Fat", itemName = "Fat", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Animal Fat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Eagle feather", itemName = "eaglef", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Eagle feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Eagle claws", itemName = "eaglet", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Eagle claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Snowy Egret beak", itemName = "egretb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Snowy Egret beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Snowy Egret feather", itemName = "egretf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Snowy Egret feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Elk antler", itemName = "elkantler", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Elk antler" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Elk pelt", itemName = "elks", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Elk pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Duck fat", itemName = "duckfat", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Duck fat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Duck Egg", itemName = "Duck_Egg", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Duck Egg" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Deer heart", itemName = "deerheart", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Deer heart" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Deer pelt", itemName = "deerpelt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Deer pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Deer skin", itemName = "deerskin", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Deer skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Deer Pelt", itemName = "deer_pelt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Deer Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Desert Iguana pelt", itemName = "dleguans", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Desert Iguana pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Crow", itemName = "crow_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Crow" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Crane beak", itemName = "darub", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Crane beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Crane feather", itemName = "daruf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Crane feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cow horn", itemName = "cowh", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cow horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cow pelt", itemName = "cows", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cow pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Coyote tooth", itemName = "coyotef", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Coyote tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Coyote Pelt", itemName = "coyotepelt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Coyote Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Coyote skin", itemName = "coyotes", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Coyote skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Coyote Pelt", itemName = "coyote_pelt", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Coyote Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cougar tooth", itemName = "cougarf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cougar tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cougar skin", itemName = "cougars", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cougar skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Condor beak", itemName = "condorb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Condor beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Condor feather", itemName = "condorf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Condor feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Chicken feather", itemName = "chickenf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Chicken feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Chicken heart", itemName = "chickenheart", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Chicken heart" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Chipmunk", itemName = "chipmunk_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Chipmunk" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cardinal bird", itemName = "cardinal_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cardinal bird" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cedar waxwing", itemName = "cedarwaxwing_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cedar waxwing" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Buck Antlers", itemName = "buckantler", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Buck Antlers" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Buck skin", itemName = "bucks", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Buck skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bull horn", itemName = "bullhorn", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bull horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bull pelt", itemName = "bulls", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bull pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Parrot beak", itemName = "bparrotb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Parrot beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Parrot feather", itemName = "bparrotf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Parrot feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Red-footed booby beak", itemName = "boobyb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Red-footed booby beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Red-footed booby feather", itemName = "boobyf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Red-footed booby feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Blue jay", itemName = "bluejay_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Blue jay" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Boar tusk", itemName = "boarmusk", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Boar tusk" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Boar pelt", itemName = "boars", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Boar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Boa Snake pelt", itemName = "boaskin", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Boa Snake pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bison horn", itemName = "bisonhorn", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bison horn" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bison pelt", itemName = "bisons", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Big Leather", itemName = "Big_Leather", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Big Leather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Beaver tail", itemName = "beavertail", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Beaver tail" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Beaver pelt", itemName = "beawers", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Beaver pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bear claws", itemName = "bearc", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bear claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bear tooth", itemName = "beart", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bear tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bat", itemName = "bat_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Bat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Black Bear skin", itemName = "bbears", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Black Bear skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cormorant beak", itemName = "bbirdb", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cormorant beak" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Cormorant feather", itemName = "bbirdf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Cormorant feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Badger skin", itemName = "badgers", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Badger skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Alligator Pelt", itemName = "aligators", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Alligator Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Alligator Tooth", itemName = "aligatorto", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Alligator Tooth" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Armadillo Claws", itemName = "armadilloc", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Armadillo Claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Armadillo Pelt", itemName = "armadillos", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Armadillo Pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Copperhead Snake pelt", itemName = "asnakes", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Copperhead Snake pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Rooster claws", itemName = "cockc", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Rooster claws" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Rooster feather", itemName = "cockf", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Rooster feather" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Robin", itemName = "robin_c", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Robin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Volture Egg", itemName = "Volture_Egg", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 50) , desc = "Sell Volture Egg" , category ="pelt", itemLimit = 0, },
        
        { itemLabel = "Legendary Alligator pelt", itemName = "legaligators", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Alligator pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Teca Alligator pelt", itemName = "legaligators1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Teca Alligator pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Sun Alligator pelt", itemName = "legaligators2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Sun Alligator pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Banded Alligator pelt", itemName = "legaligators3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Banded Alligator pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Deadly Bear pelt", itemName = "legbears1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Deadly Bear pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Owiza Bear pelt", itemName = "legbears2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Owiza Bear pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Ridgeback Spirit Bear pelt", itemName = "legbears3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Ridgeback Spirit Bear pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Golden Spirit Bear pelt", itemName = "legbears4", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Golden Spirit Bear pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Grey Beaver pelt", itemName = "legbeavers1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Grey Beaver pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary White Beaver pelt", itemName = "legbeavers2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary White Beaver pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Black Beaver pelt", itemName = "legbeavers3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Black Beaver pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Beaver pelt", itemName = "legbeawers", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Beaver pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Bison Horns", itemName = "legbisonhorn", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Bison Horns" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Bison pelt", itemName = "legbisons", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Tatanka Bison pelt", itemName = "legbisons1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Tatanka Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Winyan Bison pelt", itemName = "legbisons2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Winyan Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Payata Bison pelt", itemName = "legbisons3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Payata Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Takanta Bison pelt", itemName = "legbisonstak", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Takanta Bison pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Boar pelt", itemName = "legboars", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Boar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Cogi Boar pelt", itemName = "legboars1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Cogi Boar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Wakpa Boar pelt", itemName = "legboars2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Wakpa Boar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Icahi Boar pelt", itemName = "legboars3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Icahi Boar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Wildhog pelt", itemName = "legboars4", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Wildhog pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Buck skin", itemName = "legbucks", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Buck skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Buck pelt", itemName = "legbucks1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Buck pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Mudrunner Buck pelt", itemName = "legbucks2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Mudrunner Buck pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Snow Buck pelt", itemName = "legbucks3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Snow Buck pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Shadow Buck pelt", itemName = "legbucks4", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Shadow Buck pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Cougar skin", itemName = "legcougars", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Cougar skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Iguga Cougar pelt", itemName = "legcougars1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Iguga Cougar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Maza Cougar pelt", itemName = "legcougars2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Maza Cougar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Sapa Cougar pelt", itemName = "legcougars3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Sapa Cougar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Black Cougar pelt", itemName = "legcougars4", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Black Cougar pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Coyote skin", itemName = "legcoyotes", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Coyote skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Red Streak Coyote pelt", itemName = "legcoyotes1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Red Streak Coyote pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Midnight Paw Coyote pelt", itemName = "legcoyotes2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Midnight Paw Coyote pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Milk Coyote pelt", itemName = "legcoyotes3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Milk Coyote pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Elk Antlers", itemName = "legelkantler", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Elk Antlers" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Elk pelt", itemName = "legelks", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Elk pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Katata Elk pelt", itemName = "legelks1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Katata Elk pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Ozula Elk pelt", itemName = "legelks2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Ozula Elk pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Inahme Elk pelt", itemName = "legelks3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Inahme Elk pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Buck Antlers", itemName = "legendbuckantler", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Buck Antlers" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Boa pelt", itemName = "legendsnakes", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Boa pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Marble Fox pelt", itemName = "legfoxs2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Marble Fox pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Cross Fox pelt", itemName = "legfoxs3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Cross Fox pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Fox skin", itemName = "legfoxskin", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Fox skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Bear skin", itemName = "leggbears", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Bear skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Moose Antlers", itemName = "legmooseantler", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Moose Antlers" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Moose pelt", itemName = "legmooses", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Moose pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Snowflake Moose pelt", itemName = "legmooses1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Snowflake Moose pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Knight Moose pelt", itemName = "legmooses2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Knight Moose pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Rudy Moose pelt", itemName = "legmooses3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Rudy Moose pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Nightwalker Panther pelt", itemName = "legpanthers1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Nightwalker Panther pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Ghost Panther pelt", itemName = "legpanthers2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Ghost Panther pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Iwakta Panther pelt", itemName = "legpanthers3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Iwakta Panther pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Pronghorn skin", itemName = "legprongs", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Pronghorn skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Ram Horns", itemName = "legramhorn", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Ram Horns" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Ram pelt", itemName = "legrams", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Ram pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Gabbro Horn Ram pelt", itemName = "legrams1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Gabbro Horn Ram pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Chalk Horn Ram pelt", itemName = "legrams2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Chalk Horn Ram pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Rutile Horn Ram pelt", itemName = "legrams3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Rutile Horn Ram pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary GreatHorn Ram pelt", itemName = "legrams4", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary GreatHorn Ram pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Wolf skin", itemName = "legwolfpelt", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Wolf skin" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Emerald Wolf pelt", itemName = "legwolfs1", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Emerald Wolf pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Onyx Wolf pelt", itemName = "legwolfs2", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Onyx Wolf pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Legendary Moonstone Wolf pelt", itemName = "legwolfs3", currencyType = "cash", sellprice =55.00, randomprice = math.random(28, 82), desc = "Sell Legendary Moonstone Wolf pelt" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Compass", itemName = "compass", currencyType = "cash", sellprice =5.00, randomprice = math.random(2, 8) /50, desc = "Sell Compass" , category ="Maptools", itemLimit = 0, },
        { itemLabel = "Alligator Meat", itemName = "aligatorMeat", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Alligator Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Bacon", itemName = "bacon", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Bacon" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Beef", itemName = "beef", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Beef" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Big Game Meat", itemName = "biggame", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Big Game Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Herptile Meat", itemName = "herptile", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Herptile Meat" , category = "pelt", itemLimit = 0, },
        { itemLabel = "Bird Meat", itemName = "bird", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Bird Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Steak", itemName = "steak", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Steak" , category = "pelt", itemLimit = 0, },
        { itemLabel = "Game Meat", itemName = "game", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Game Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Gamey Meat", itemName = "Gamey_Meat", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Gamey Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Meat", itemName = "Meat", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Meat" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Mutton", itemName = "Mutton", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Mutton" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Pork", itemName = "pork", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Pork" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Raw Bacon", itemName = "raw_bacon", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Raw Bacon" , category ="pelt", itemLimit = 0, },
        { itemLabel = "Stringy Meat", itemName = "stringy", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Stringy Meat" , category = "pelt", itemLimit = 0, },
        { itemLabel = "Fresh Pork ", itemName = "salamelle", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Fresh Pork " , category ="pelt", itemLimit = 0, },
        { itemLabel = "Venison", itemName = "venison", currencyType = "cash", sellprice = 1.50, randomprice = math.random(1, 2) /50, desc = "Sell Venison" , category ="pelt", itemLimit = 0, },

 },

 horsecare = {
    {
        itemLabel = "horse brush",
        itemName = "horsebrush",
        currencyType = "cash",
        sellprice = 1,
        randomprice = math.random(1, 2),
        desc = "sell",
        category = "horsecare",
        itemLimit = 0,
    }
},

}
